### ISSUE TITLE
the latest code running error

### ISSUE THREAD

**Issue by chenyoufu** [epsylon/xsser-public#1]
XSSer v1.7 (beta): "Total Swarm!" - 2013 - (GPLv3.0) -> by psy

Testing [XSS from URL] injections... looks like your target is good defined ;)

```
Internal error getting -payloads- error
Traceback (most recent call last):
  File "/root/xsser-public/xsser-public/core/main.py", line 1437, in try_running
    return func(*args)
  File "/root/xsser-public/xsser-public/core/main.py", line 285, in get_payloads
    payloads_css    = core.fuzzing.vectors.vectors_css
AttributeError: 'module' object has no attribute 'vectors_css'

HEAD alive check for the target: (http://www.baidu.com?a=b) is OK(200) [AIMED]


Internal problems running attack:  error
Traceback (most recent call last):
  File "/root/xsser-public/xsser-public/core/main.py", line 1437, in try_running
    return func(*args)
  File "/root/xsser-public/xsser-public/core/main.py", line 1688, in attack
    self.attack_url(url, payloads, query_string)
  File "/root/xsser-public/xsser-public/core/main.py", line 641, in attack_url
    for payload in payloads:
TypeError: 'NoneType' object is not iterable
```

Mosquito(s) landed!

**Comment by epsylon** [comment]
Hi chenyoufu,

This error is because you haven't module 'vectors_css' on your code. This was implemented supodesly during GSoC2013 with the idea of include CSS injections.

From where are you taking code?. If is frome github, please tell me to fix it.

Thanks for your report.

**Comment by epsylon** [comment]
Hi chenyoufu,

This error is because you haven't module 'vectors_css' on your code. This was implemented supodesly during GSoC2013 with the idea of include CSS injections.

From where are you taking code?. If is frome github, please tell me to fix it.

Thanks for your report.
