### ISSUE TITLE
Error of installation on windows7 64bits & python2.7 64bits

### ISSUE THREAD

**Issue by chuiy** [epsylon/xsser-public#15]
hi, when i install with command "python setup.py install", the console prints error as follows:

running install_data
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    test_suite = "tests"
  File "C:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "C:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 67, i
n run
    self.do_egg_install()
  File "C:\Python27\lib\site-packages\setuptools\command\install.py", line 109,
in do_egg_install
    self.run_command('bdist_egg')
  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\site-packages\setuptools\command\bdist_egg.py", line 181
, in run
    self.do_install_data()
  File "C:\Python27\lib\site-packages\setuptools\command\bdist_egg.py", line 133
, in do_install_data
    self.call_command('install_data', force=0, root=None)
  File "C:\Python27\lib\site-packages\setuptools\command\bdist_egg.py", line 147
, in call_command
    self.run_command(cmdname)
  File "C:\Python27\lib\distutils\cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "C:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Python27\lib\distutils\command\install_data.py", line 58, in run
    dir = convert_path(f[0])
  File "C:\Python27\lib\distutils\util.py", line 124, in convert_path
    raise ValueError, "path '%s' cannot be absolute" % pathname
ValueError: path '/usr/share/doc/xsser/' cannot be absolute

Has anyone solved the same problem?  Looking forward to ur help. Thanks!

**Comment by epsylon** [comment]
Hi,
This is related with pathlib. To have more information about that error, you can add --log install.log to your command. This will generates a file with detailed information. 
Please, share with us that log.

**Comment by dhanumurti** [comment]
Hi @chuiy  i've made Windows Version of Xsser here : https://github.com/dhanumurti/casperx the installation is very easy like any other windows program

**Comment by epsylon** [comment]
@dhanumurti XSSer is written in Python which can be multiplatform executed. 
Have not so much sense to fork it for Win32 exclusively, I think...

**Comment by dhanumurti** [comment]
yeah @epsylon but when first time i try to install xsser on windows i got so much error not like linux it works very well. I just made easiest way for windows user like me by editing your setup.py so it suitable for windows filesystem and made auto installer with batch script

Thanks for a great tools, btw i'm new at python programming the -gtk gui version of xsser not work in windows how can i fix that?

**Comment by epsylon** [comment]
Hi @dhanumurti 
I understand your effort but I think that sometimes is better try to search/solve problems on main package than forking it, so ppl doesn't lost original sources.
Otherwise, your description of the "problem" that you have is so poor. 
Please, try to add more tips (such as: Win32 version, python version, python GTK/Glade,.., etc..)
For example, try first to install correctly this libs: **http://xsser.03c8.net/#installation**

**Comment by dhanumurti** [comment]
ok @epsylon should i remove my repo ?

**Comment by epsylon** [comment]
@dhanumurti That as you wish... 
Are you gonna give support to all XSSer/win32 users without having in mind "root" source code?. Doesn't looks a good idea so maybe is better to have your efforts to solve bugs here than on a different fork.
