### ISSUE TITLE
socket.error [Errno 57] Socket is not connected

### ISSUE THREAD

**Issue by daton89** [epsylon/xsser-public#9]
Hello, 

I'm running xsser with --wizard with target mysite and with all other default settings 

after connection it run max 2 test and then it return this error:

> Traceback (most recent call last):
  File "/usr/local/bin/xsser", line 5, in <module>
    pkg_resources.run_script('xsser==1.6', 'xsser')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 492, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 1350, in run_script
    execfile(script_filename, namespace, namespace)
  File "/Library/Python/2.7/site-packages/xsser-1.6-py2.7.egg/EGG-INFO/scripts/xsser", line 38, in <module>
    app.land(True)
  File "/Library/Python/2.7/site-packages/xsser-1.6-py2.7.egg/core/main.py", line 1966, in land
    self.hub.shutdown()
  File "/Library/Python/2.7/site-packages/xsser-1.6-py2.7.egg/core/tokenhub.py", line 66, in shutdown
    self.socket.shutdown(socket.SHUT_RDWR)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
> socket.error: [Errno 57] Socket is not connected

how can i fix it?

**Comment by epsylon** [comment]
Hi,
Which OS are you using?. It look something wrong with sockets?. 

Looks that sockets are not closes propertly after use it.. By the way, XSSer has a version 1.7. Maybe you should try to update it to latest and try again.

**Comment by tonillo** [comment]
i'm using mac 10.11

**Comment by epsylon** [comment]
Did you upgraded tool to latest release (v1.7)?

**Comment by Duffyx** [comment]
This is still relevant, on FreeBSD I have this:

2019-03-22 19:40:33: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-03-22 19:41:04: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-03-22 19:41:05: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-03-22 19:41:06: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-03-22 19:41:07: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-03-22 19:41:08: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-03-22 19:41:09: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-03-22 19:41:10: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected
2019-03-22 19:41:11: python.d ERROR: unbound[local] : [Errno 57] Socket is not connected.

Unbound graphs are generated fine; just logs that are flooding.

**Comment by epsylon** [comment]
@Duffyx Ok, so is a warning message. Btw, which sockets do you have listening on when running XSSer?.
> https://stackoverflow.com/questions/55032621/oserror-errno-57-socket-is-not-connected
Can you check that?

**Comment by Duffyx** [comment]
What do you want me to exactly check please?
How they solved it in that thread and see if it helps?

**Comment by epsylon** [comment]
@Duffyx It is a message sent by unbound ("validating, recursive, caching DNS resolver") that warning you about some failing connections. Isn't related with XSSer..
